export const PHYSICS = {
  rulesetVersion: "V2.1",
  voxelEdgeM: 0.2,
  stoneMassKg: 21.6,
  balanceMarginCells: 0.05,
  baseHorizontalReachCells: 4,
  thicknessReachBonusPerDoublingCells: 1,
  maximumHorizontalReachCells: 8,
  maximumSlendernessRatio: 10,
  maximumLoadPerAnchorCell: 4_096,
  minimumTunnelRoofCells: 2,
  maximumTunnelRadiusCells: 3,
  maximumAffectedStoneCells: 10_000,
  maximumDistinctStoneLevels: 250,
  maximumCavityWindowCells: 64 ** 3,
  maximumTouchedPhysicsChunks: 8,
  worldBoundsM: 50_000,
} as const;

export const CLIMBER = {
  bodyMassKg: 78,
  baseCampRadiusM: 140,
  protectedSpawnRadiusM: 20,
  interactionReachM: 1.25,
  maxProofSegmentM: 45,
  maxWalkStepM: 0.42,
  maxWalkSlopeDegrees: 35,
  maxLoadedWalkSlopeDegrees: 32,
  maxScrambleSlopeDegrees: 55,
  maxLoadedScrambleSlopeDegrees: 48,
  maxClimbSlopeDegrees: 82,
  walkSpeedMps: 0.78,
  scrambleSpeedMps: 0.34,
  climbSpeedMps: 0.16,
  enduranceCapacity: 100,
  kilojoulesPerEndurance: 450,
  rockTerrainFactor: 1.15,
  snowTerrainFactor: 1.62,
  iceTerrainFactor: 1.36,
} as const;

export const TERRAIN = {
  voxelEdgeM: PHYSICS.voxelEdgeM,
  physicsChunkEdgeM: 32,
  streamTileEdgeM: 256,
  naturalizationVersion: "ae-surface-v1",
  naturalizationSeed: 0x41_45_56_31,
  maximumSyntheticReliefM: 0.42,
} as const;
